### ISSUE TITLE
SEFSC Cohort Setup Checklist

### ISSUE THREAD

**Issue by jules32** [Openscapes/2022-noaa-sefsc-summer#1]
This issue is to help track the pre-cohort setup, following the [approach-guide](https://openscapes.github.io/approach-guide/champions/pre-cohort-tech.html#cohort-planning-checklist-github-issue). These TODO's are for @jules32 and also will include @stefaniebutland, as well as Ady and Molly

## Quicklinks

- Planning Google Folder ([SEFSC planning](https://drive.google.com/drive/folders/1qZrhgme_tQ0LeXfRutC5YmFaWvO0H6ZJ)), includes Planning Doc that also serves for Seaside Chats and Debriefs
  - [LessonPlannning Spreadsheet]  
  - [PlanningDoc](https://docs.google.com/document/d/1pUBTzkPAsBbm66Vk41wdWJJIvF9C8DON9Edrk0HG7ls/edit#)
- [Cohort Folder](https://drive.google.com/drive/folders/1TzOVeUSNzoS_fD1IBimm5gFtz2WP4etS?usp=sharing) - to share with Champions (a subfolder within planning folder)
  - [ParticipantsList](https://docs.google.com/spreadsheets/d/1XtRex6YBIkBgKkY-APlLvQC7iqGEnnp6k6bXDxVg1gg/edit#gid=1525286866)

## Prep Announcement

- [x] draft events page (https://openscapes.github.io/events)
- [x] create google form - Ady made and internal spreadsheet
- [x] post events page (with linked google form)

## Tech Setup for Cohort 
For Cohort Planning Team  (Stef, Julie, Ady)

- [x] invite co-leads/assists to Google Calendar Cohort Calls
- [x] GitHub:
  - [x] create GitHub repo for cohort with cohort name: eg github.com/openscapes/2022-noaa-sefsc-summer
  - [x] Make it a website: Settings > Pages > Source: main, dir: root
  - [x] Add our Code of Conduct (kyber)
  - [x]  Write Cohort info on the README (kyber)
  -  *Add Evaluation information upcoming*
  - [x] Add co-leads/assists to GitHub repo with maintainer permission
  - [x] create Cohort Planning Checklist Issues, tag planning team
- [x] Google Folder:
  - [x] create Google Folder for participants: `Openscapes_CohortCalls [ 2022-noaa-sefsc-summer ]` 
  - [x] add co-leads/assists to Google Folder for participants

## Adding Participants (giving access at the right time)

- [x] Emails
  - [x] draft welcome email
  - [x] send welcome email
  - [x] send "reminder" email 1 day before, after adding participants to `Openscapes_CohortCalls [ 2022-noaa-sefsc-summer ]`
- [x] Google Calendar:
  - [x] add participants emails to Google Calendar Invites: Cohort Calls - Do this when you send Welcome Email
  - [x] add Google Folder link to the Google Calendar description: 

  > We'll meet with the above Google Meet link. 
  > [Openscapes_CohortCalls] is our Cohort Folder that will have Agendas prior to each call

- [x] Google Folder: 
  - [x] add participants emails to `Openscapes_CohortCalls [ 2022-noaa-sefsc-summer ]` - Do this the day before Cohort Call 1

## Adding Participants: After Call 1
  
- [x] Slack
  - [x] Add participant emails to Slack; create cohort channel - Do this after Cohort Call 1
- [x] Google Calendar
  - [x] add participants emails to Google Calendar Invites: Co-working times (optional) - Do this after Cohort Call 1

## Adding Participants: Before Call 2

- [x] GitHub:
  - [x] add participants to GitHub repo with `kyber` - Do this before GitHub Clinic 
  - [x] create GitHub Clinic files with `kyber` - Do this before GitHub Clinic

**Comment by jules32** [comment]
Hi @stefaniebutland and @AdyanRios-NOAA creating this issue for planning and tagging you but nothing needed at this point!

**Comment by jules32** [comment]
Hi @stefaniebutland and Ady, I've drafted the welcome email and will plan to send it later today, along with adding folks to the 5 Cohort Calls Calendar invites

**Comment by AdyanRios-NOAA** [comment]
@jules32 Our 40 participants are confirmed! The emails are the top 40 emails listed here on the second tab [here](https://docs.google.com/spreadsheets/d/1XtRex6YBIkBgKkY-APlLvQC7iqGEnnp6k6bXDxVg1gg/edit?usp=sharing))

**Comment by jules32** [comment]
Woohoo! Thanks Ady! I'll check in with you on Tuesday to confirm before sending the welcome email out and sending calendar invites. Have a good weekend!
